### ISSUE TITLE
cbsd_bacula.html needs auto-translation

### ISSUE THREAD

**Issue by miker** [cbsd/cbsd-wwwdoc#7]
Hello, cbsd-wwwdoc/en/articles/cbsd_bacula.html just loads ru/articles/cbsd_bacula.html. I can read the article via google translate, but it makes it much easier for me to re-write if I have the already translated version to hack on.

**Comment by miker** [comment]
There are actually quite a few that just load the ru version. Should I open an issue for each one?

**Comment by olevole** [comment]
Hello. I'm not sure that it makes sense to translate. This article was written in 2013 and is probably very outdated. Most likely, it was not planned to be translated, because it is not on the page https://www.bsdstore.ru/en/articles.html
I need to review the original first and update the current integration capabilities between CBSD and Bacula (or Bareos, fork of the Bacula).

**Comment by miker** [comment]
I think you are right about the article being old, and probably not being worth translating. I was just looking at the articles via the articles dir in the repo not the website.

**Comment by olevole** [comment]
Well, in that case, I'll close this issue. If you want to help with correcting the english text, it's best to look at this pages:

https://www.bsdstore.ru/en/articles.html
https://www.bsdstore.ru/en/docs.html

Thank you!

**Comment by miker** [comment]
Not a problem, glad to help.
